# 📂 Working with JSON Data & SQL using Python

---

## 🧠 Overview

In this section, we will work with:

- 📄 JSON datasets  
- 🗄️ SQL operations using Python  

> These are very important in real-world Machine Learning because data often comes from APIs (JSON) and databases (SQL).

---

## 📄 Part 1: Working with JSON Data

---

### 📌 What is JSON?

- JSON = JavaScript Object Notation  
- Lightweight data format  
- Commonly used in APIs  

---

### ⚙️ Step 1: Import Libraries

```python
import pandas as pd
import json

In [1]:
import pandas as pd
import json
from pandas import json_normalize

In [2]:
file_path="/Users/ap_018/ML/ML/All_Data_Files/iris.json"
df=pd.read_json(file_path)

In [3]:
df

     sepalLength  sepalWidth  petalLength  petalWidth    species
0            5.1         3.5          1.4         0.2     setosa
1            4.9         3.0          1.4         0.2     setosa
2            4.7         3.2          1.3         0.2     setosa
3            4.6         3.1          1.5         0.2     setosa
4            5.0         3.6          1.4         0.2     setosa
..           ...         ...          ...         ...        ...
145          6.7         3.0          5.2         2.3  virginica
146          6.3         2.5          5.0         1.9  virginica
147          6.5         3.0          5.2         2.0  virginica
148          6.2         3.4          5.4         2.3  virginica
149          5.9         3.0          5.1         1.8  virginica

[150 rows x 5 columns]

In [4]:
print(df.head())
df.info()

   sepalLength  sepalWidth  petalLength  petalWidth species
0          5.1         3.5          1.4         0.2  setosa
1          4.9         3.0          1.4         0.2  setosa
2          4.7         3.2          1.3         0.2  setosa
3          4.6         3.1          1.5         0.2  setosa
4          5.0         3.6          1.4         0.2  setosa
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   sepalLength  150 non-null    float64
 1   sepalWidth   150 non-null    float64
 2   petalLength  150 non-null    float64
 3   petalWidth   150 non-null    float64
 4   species      150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

# 📄 Understanding JSON Normalization using Pandas

---

## 🧠 Overview

In real-world Machine Learning projects, data often comes in **JSON format**, especially from APIs.

However, JSON data is usually **nested and unstructured**, which is not suitable for analysis.

> 📌 To solve this, we use **`json_normalize()`** to convert JSON into a structured table (DataFrame).

---

## ⚙️ Code Example

```python
import json
import pandas as pd
from pandas import json_normalize

with open("data.json") as f:
    data = json.load(f)

df = json_normalize(data)

In [5]:
with open(file_path) as f:
    data=json.load(f)
df=json_normalize(data)

In [6]:
df

     sepalLength  sepalWidth  petalLength  petalWidth    species
0            5.1         3.5          1.4         0.2     setosa
1            4.9         3.0          1.4         0.2     setosa
2            4.7         3.2          1.3         0.2     setosa
3            4.6         3.1          1.5         0.2     setosa
4            5.0         3.6          1.4         0.2     setosa
..           ...         ...          ...         ...        ...
145          6.7         3.0          5.2         2.3  virginica
146          6.3         2.5          5.0         1.9  virginica
147          6.5         3.0          5.2         2.0  virginica
148          6.2         3.4          5.4         2.3  virginica
149          5.9         3.0          5.1         1.8  virginica

[150 rows x 5 columns]

## Working with SQL

In [7]:
!pip install mysql.connector

Requirement already satisfied: mysql.connector in /opt/anaconda3/lib/python3.12/site-packages (2.2.9)

In [8]:
import mysql.connector

In [9]:
conn= mysql.connector.connect(host="localhost",user="root",password='',database="world")

In [10]:
sql_df=pd.read_sql_query("select * from country where SurfaceArea > 1000",conn)

/var/folders/qm/5y4s4wyj5c9dcyd20_qy23b80000gn/T/ipykernel_3683/3443796962.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  sql_df=pd.read_sql_query("select * from country where SurfaceArea > 1000",conn)

In [11]:
sql_df

,Code,Name,Continent,Region,SurfaceArea,IndepYear,Population,LifeExpectancy,GNP,GNPOld,LocalName,GovernmentForm,HeadOfState,Capital,Code2
0,AFG,Afghanistan,Asia,Southern and Central Asia,652090.0,1919.0,22720000,45.9,5976.0,NaN,Afganistan/Afqanestan,Islamic Emirate,Mohammad Omar,1.0,AF
1,AGO,Angola,Africa,Central Africa,1246700.0,1975.0,12878000,38.3,6648.0,7984.0,Angola,Republic,José Eduardo dos Santos,56.0,AO
2,ALB,Albania,Europe,Southern Europe,28748.0,1912.0,3401200,71.6,3205.0,2500.0,Shqipëria,Republic,Rexhep Mejdani,34.0,AL
3,ARE,United Arab Emirates,Asia,Middle East,83600.0,1971.0,2441000,74.1,37966.0,36846.0,Al-Imarat al-´Arabiya al-Muttahida,Emirate Federation,Zayid bin Sultan al-Nahayan,65.0,AE
4,ARG,Argentina,South America,South America,2780400.0,1816.0,37032000,75.1,340238.0,323310.0,Argentina,Federal Republic,Fernando de la Rúa,69.0,AR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180,YEM,Yemen,Asia,Middle East,527968.0,1918.0,18112000,59.8,6041.0,5729.0,Al-Yaman,Republic,Ali Abdallah Salih,1780.0,YE
181,YUG,Yugoslavia,Europe,Southern Europe,102173.0,1918.0,10640000,72.4,17000.0,NaN,Jugoslavija,Federal Republic,Vojislav Koštunica,1792.0,YU
182,ZAF,South Africa,Africa,Southern Africa,1221037.0,1910.0,40377000,51.1,116729.0,129092.0,South Africa,Republic,Thabo Mbeki,716.0,ZA
183,ZMB,Zambia,Africa,Eastern Africa,752618.0,1964.0,9169000,37.2,3377.0,3922.0,Zambia,Republic,Frederick Chiluba,3162.0,ZM
184,ZWE,Zimbabwe,Africa,Eastern Africa,390757.0,1980.0,11669000,37.8,5951.0,8670.0,Zimbabwe,Republic,Robert G. Mugabe,4068.0,ZW

In [12]:
pd.read_sql_query("select sum(LifeExpectancy),Continent from country where Capital between 500 and 3000 group by Continent",conn)

/var/folders/qm/5y4s4wyj5c9dcyd20_qy23b80000gn/T/ipykernel_3683/1944365942.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("select sum(LifeExpectancy),Continent from country where Capital between 500 and 3000 group by Continent",conn)

   sum(LifeExpectancy)      Continent
0               2171.0           Asia
1               1739.4         Europe
2               1519.7  North America
3               1874.8         Africa
4                678.7        Oceania
5                424.8  South America

In [13]:
print(pd.read_sql("select * from country",conn).columns)
print()
print(pd.read_sql("select * from city",conn).columns)
print()
print(pd.read_sql("select * from countrylanguage",conn).columns)
print()

Index(['Code', 'Name', 'Continent', 'Region', 'SurfaceArea', 'IndepYear',
       'Population', 'LifeExpectancy', 'GNP', 'GNPOld', 'LocalName',
       'GovernmentForm', 'HeadOfState', 'Capital', 'Code2'],
      dtype='object')

Index(['ID', 'Name', 'CountryCode', 'District', 'Population'], dtype='object')

Index(['CountryCode', 'Language', 'IsOfficial', 'Percentage'], dtype='object')

/var/folders/qm/5y4s4wyj5c9dcyd20_qy23b80000gn/T/ipykernel_3683/2831979216.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  print(pd.read_sql("select * from country",conn).columns)
/var/folders/qm/5y4s4wyj5c9dcyd20_qy23b80000gn/T/ipykernel_3683/2831979216.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  print(pd.read_sql("select * from city",conn).columns)
/var/folders/qm/5y4s4wyj5c9dcyd20_qy23b80000gn/T/ipykernel_3683/2831979216.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  print(pd.read_sql("select * from countrylanguage",conn).columns)

In [19]:
c=pd.read_sql_query("select * from country",conn)
c

/var/folders/qm/5y4s4wyj5c9dcyd20_qy23b80000gn/T/ipykernel_3683/857415736.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  c=pd.read_sql_query("select * from country",conn)

,Code,Name,Continent,Region,SurfaceArea,IndepYear,Population,LifeExpectancy,GNP,GNPOld,LocalName,GovernmentForm,HeadOfState,Capital,Code2
0,ABW,Aruba,North America,Caribbean,193.0,NaN,103000,78.4,828.0,793.0,Aruba,Nonmetropolitan Territory of The Netherlands,Beatrix,129.0,AW
1,AFG,Afghanistan,Asia,Southern and Central Asia,652090.0,1919.0,22720000,45.9,5976.0,NaN,Afganistan/Afqanestan,Islamic Emirate,Mohammad Omar,1.0,AF
2,AGO,Angola,Africa,Central Africa,1246700.0,1975.0,12878000,38.3,6648.0,7984.0,Angola,Republic,José Eduardo dos Santos,56.0,AO
3,AIA,Anguilla,North America,Caribbean,96.0,NaN,8000,76.1,63.2,NaN,Anguilla,Dependent Territory of the UK,Elisabeth II,62.0,AI
4,ALB,Albania,Europe,Southern Europe,28748.0,1912.0,3401200,71.6,3205.0,2500.0,Shqipëria,Republic,Rexhep Mejdani,34.0,AL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
234,YEM,Yemen,Asia,Middle East,527968.0,1918.0,18112000,59.8,6041.0,5729.0,Al-Yaman,Republic,Ali Abdallah Salih,1780.0,YE
235,YUG,Yugoslavia,Europe,Southern Europe,102173.0,1918.0,10640000,72.4,17000.0,NaN,Jugoslavija,Federal Republic,Vojislav Koštunica,1792.0,YU
236,ZAF,South Africa,Africa,Southern Africa,1221037.0,1910.0,40377000,51.1,116729.0,129092.0,South Africa,Republic,Thabo Mbeki,716.0,ZA
237,ZMB,Zambia,Africa,Eastern Africa,752618.0,1964.0,9169000,37.2,3377.0,3922.0,Zambia,Republic,Frederick Chiluba,3162.0,ZM
238,ZWE,Zimbabwe,Africa,Eastern Africa,390757.0,1980.0,11669000,37.8,5951.0,8670.0,Zimbabwe,Republic,Robert G. Mugabe,4068.0,ZW

4074.0

In [20]:
ci=pd.read_sql_query("select * from city",conn)
ci

/var/folders/qm/5y4s4wyj5c9dcyd20_qy23b80000gn/T/ipykernel_3683/898832052.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  ci=pd.read_sql_query("select * from city",conn)

        ID            Name CountryCode       District  Population
0        1           Kabul         AFG          Kabol     1780000
1        2        Qandahar         AFG       Qandahar      237500
2        3           Herat         AFG          Herat      186800
3        4  Mazar-e-Sharif         AFG          Balkh      127800
4        5       Amsterdam         NLD  Noord-Holland      731200
...    ...             ...         ...            ...         ...
4074  4075      Khan Yunis         PSE     Khan Yunis      123175
4075  4076          Hebron         PSE         Hebron      119401
4076  4077        Jabaliya         PSE     North Gaza      113901
4077  4078          Nablus         PSE         Nablus      100231
4078  4079           Rafah         PSE          Rafah       92020

[4079 rows x 5 columns]

In [21]:
cl=pd.read_sql_query("select * from countrylanguage",conn)
cl

/var/folders/qm/5y4s4wyj5c9dcyd20_qy23b80000gn/T/ipykernel_3683/3373975284.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  cl=pd.read_sql_query("select * from countrylanguage",conn)

    CountryCode    Language IsOfficial  Percentage
0           ABW       Dutch          T         5.3
1           ABW     English          F         9.5
2           ABW  Papiamento          F        76.7
3           ABW     Spanish          F         7.4
4           AFG     Balochi          F         0.9
..          ...         ...        ...         ...
979         ZMB      Tongan          F        11.0
980         ZWE     English          T         2.2
981         ZWE     Ndebele          F        16.2
982         ZWE      Nyanja          F         2.2
983         ZWE       Shona          F        72.1

[984 rows x 4 columns]









🧠 🔹 GROUP BY & HAVING
Find continents where average life expectancy is greater than 70.
Identify countries that have more than 3 official languages.
🧠 🔹 COMPLEX JOINS
Find cities whose population is greater than the average population of their respective country.
Find countries where no city exists (i.e., countries without cities in the dataset).
🧠 🔹 CASE & CONDITIONAL LOGIC
Categorize countries into 'High', 'Medium', and 'Low' population groups based on thresholds.
🧠 🔹 DATA ANALYSIS TYPE
Calculate the percentage of official languages for each country.
Find the continent with the highest average GNP.
🧠 🔹 SELF JOIN / ADVANCED
Find pairs of countries having similar population (difference within 10%).
🧠 🔹 STRING / FILTERING
Find countries starting with the letter 'A' whose population is above global average.
🧠 🔹 REAL-WORLD THINKING
Find the continent that contains the city with the highest population.

# 🧠 🔹 JOINS & AGGREGATION

### 1.Find the top 5 countries with the highest number of cities.

In [29]:
pd.read_sql_query("select c.Name,count(ct.ID) as city_count from country c join city ct on c.Code=ct.CountryCode group by c.Name order by  city_count desc limit 5",conn)

/var/folders/qm/5y4s4wyj5c9dcyd20_qy23b80000gn/T/ipykernel_3683/423227300.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("select c.Name,count(ct.ID) as city_count from country c join city ct on c.Code=ct.CountryCode group by c.Name order by  city_count desc limit 5",conn)

            Name  city_count
0          China         363
1          India         341
2  United States         274
3         Brazil         250
4          Japan         248

### 2. Calculate continent-wise total population.

In [30]:
pd.read_sql_query("select c.Continent, sum(c.Population) as total_population from country c group by c.Continent order by total_population",conn)

/var/folders/qm/5y4s4wyj5c9dcyd20_qy23b80000gn/T/ipykernel_3683/52250070.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("select c.Continent, sum(c.Population) as total_population from country c group by c.Continent order by total_population",conn)

       Continent  total_population
0     Antarctica      0.000000e+00
1        Oceania      3.040115e+07
2  South America      3.457800e+08
3  North America      4.829930e+08
4         Europe      7.300746e+08
5         Africa      7.844750e+08
6           Asia      3.705026e+09

### 3.Find the country with the highest population in each continent.

In [38]:
pd.read_sql_query("select Name,Population from country c1 where Population=(select max(Population) from country c2 where c1.Continent=c2.Continent)",conn)

/var/folders/qm/5y4s4wyj5c9dcyd20_qy23b80000gn/T/ipykernel_3683/2046301535.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("select Name,Population from country c1 where Population=(select max(Population) from country c2 where c1.Continent=c2.Continent)",conn)

                                            Name  Population
0                                     Antarctica           0
1                    French Southern territories           0
2                                      Australia    18886000
3                                         Brazil   170115000
4                                  Bouvet Island           0
5                                          China  1277558000
6              Heard Island and McDonald Islands           0
7                                        Nigeria   111506000
8                             Russian Federation   146934000
9   South Georgia and the South Sandwich Islands           0
10                                 United States   278357000

### 4.List countries along with their capital city names.

In [43]:
pd.read_sql_query("select c.Name ,ct.Name as capital_name from country c join city ct on c.Code=ct.CountryCode where c.Capital=ct.ID",conn)

/var/folders/qm/5y4s4wyj5c9dcyd20_qy23b80000gn/T/ipykernel_3683/1466704480.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("select c.Name ,ct.Name as capital_name from country c join city ct on c.Code=ct.CountryCode where c.Capital=ct.ID",conn)

             Name capital_name
0           Aruba   Oranjestad
1     Afghanistan        Kabul
2          Angola       Luanda
3        Anguilla   The Valley
4         Albania       Tirana
..            ...          ...
227         Yemen        Sanaa
228    Yugoslavia      Beograd
229  South Africa     Pretoria
230        Zambia       Lusaka
231      Zimbabwe       Harare

[232 rows x 2 columns]

# 🧠 🔹 SUBQUERIES


### 5.Find cities whose population is greater than the average city population.

In [48]:
pd.read_sql_query("select Name from city where Population > (select avg(Population) from city )",conn)

/var/folders/qm/5y4s4wyj5c9dcyd20_qy23b80000gn/T/ipykernel_3683/1618927453.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("select Name from city where Population > (select avg(Population) from city )",conn)

                 Name
0               Kabul
1           Amsterdam
2           Rotterdam
3                Haag
4               Alger
..                ...
870             Miami
871  Colorado Springs
872            Harare
873          Bulawayo
874              Gaza

[875 rows x 1 columns]

### 6.Find countries where life expectancy is higher than the global average.

In [49]:
c

,Code,Name,Continent,Region,SurfaceArea,IndepYear,Population,LifeExpectancy,GNP,GNPOld,LocalName,GovernmentForm,HeadOfState,Capital,Code2
0,ABW,Aruba,North America,Caribbean,193.0,NaN,103000,78.4,828.0,793.0,Aruba,Nonmetropolitan Territory of The Netherlands,Beatrix,129.0,AW
1,AFG,Afghanistan,Asia,Southern and Central Asia,652090.0,1919.0,22720000,45.9,5976.0,NaN,Afganistan/Afqanestan,Islamic Emirate,Mohammad Omar,1.0,AF
2,AGO,Angola,Africa,Central Africa,1246700.0,1975.0,12878000,38.3,6648.0,7984.0,Angola,Republic,José Eduardo dos Santos,56.0,AO
3,AIA,Anguilla,North America,Caribbean,96.0,NaN,8000,76.1,63.2,NaN,Anguilla,Dependent Territory of the UK,Elisabeth II,62.0,AI
4,ALB,Albania,Europe,Southern Europe,28748.0,1912.0,3401200,71.6,3205.0,2500.0,Shqipëria,Republic,Rexhep Mejdani,34.0,AL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
234,YEM,Yemen,Asia,Middle East,527968.0,1918.0,18112000,59.8,6041.0,5729.0,Al-Yaman,Republic,Ali Abdallah Salih,1780.0,YE
235,YUG,Yugoslavia,Europe,Southern Europe,102173.0,1918.0,10640000,72.4,17000.0,NaN,Jugoslavija,Federal Republic,Vojislav Koštunica,1792.0,YU
236,ZAF,South Africa,Africa,Southern Africa,1221037.0,1910.0,40377000,51.1,116729.0,129092.0,South Africa,Republic,Thabo Mbeki,716.0,ZA
237,ZMB,Zambia,Africa,Eastern Africa,752618.0,1964.0,9169000,37.2,3377.0,3922.0,Zambia,Republic,Frederick Chiluba,3162.0,ZM
238,ZWE,Zimbabwe,Africa,Eastern Africa,390757.0,1980.0,11669000,37.8,5951.0,8670.0,Zimbabwe,Republic,Robert G. Mugabe,4068.0,ZW

In [51]:
pd.read_sql_query("select Name ,LifeExpectancy from country where LifeExpectancy > (select avg(LifeExpectancy) from country)",conn)

/var/folders/qm/5y4s4wyj5c9dcyd20_qy23b80000gn/T/ipykernel_3683/4241937887.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("select Name ,LifeExpectancy from country where LifeExpectancy > (select avg(LifeExpectancy) from country)",conn)

                        Name  LifeExpectancy
0                      Aruba            78.4
1                   Anguilla            76.1
2                    Albania            71.6
3                    Andorra            83.5
4       Netherlands Antilles            74.7
..                       ...             ...
135  Virgin Islands, British            75.4
136     Virgin Islands, U.S.            78.1
137                  Vietnam            69.3
138                    Samoa            69.2
139               Yugoslavia            72.4

[140 rows x 2 columns]

### 7.Find countries whose population is greater than the average population of their continent.

In [52]:
pd.read_sql_query("select Name,Population from country where Population > (select AVG(population) from country) ",conn)

/var/folders/qm/5y4s4wyj5c9dcyd20_qy23b80000gn/T/ipykernel_3683/2185555036.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("select Name,Population from country where Population > (select AVG(population) from country) ",conn)

                                     Name  Population
0                               Argentina    37032000
1                              Bangladesh   129155000
2                                  Brazil   170115000
3                                  Canada    31147000
4                                   China  1277558000
5   Congo, The Democratic Republic of the    51654000
6                                Colombia    42321000
7                                 Germany    82164700
8                                 Algeria    31471000
9                                   Egypt    68470000
10                                  Spain    39441700
11                               Ethiopia    62565000
12                                 France    59225700
13                         United Kingdom    59623400
14                              Indonesia   212107000
15                                  India  1013662000
16                                   Iran    67702000
17                                  Italy    57680000
18                                  Japan   126714000
19                                  Kenya    30080000
20                            South Korea    46844000
21                                Morocco    28351000
22                                 Mexico    98881000
23                                Myanmar    45611000
24                                Nigeria   111506000
25                               Pakistan   156483000
26                                   Peru    25662000
27                            Philippines    75967000
28                                 Poland    38653600
29                     Russian Federation   146934000
30                                  Sudan    29490000
31                               Thailand    61399000
32                                 Turkey    66591000
33                               Tanzania    33517000
34                                Ukraine    50456000
35                          United States   278357000
36                                Vietnam    79832000
37                           South Africa    40377000

# 🧠 🔹 WINDOW FUNCTIONS

### 8.Rank countries by population within each continent.

In [56]:
pd.read_sql_query("select Name,Continent, rank() over (partition by continent order by  Population desc ) as rank from country",conn)

/var/folders/qm/5y4s4wyj5c9dcyd20_qy23b80000gn/T/ipykernel_3683/2876632391.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("select Name,Continent, rank() over (partition by continent order by  Population desc ) as rank from country",conn)

                 Name      Continent  rank
0               China           Asia     1
1               India           Asia     2
2           Indonesia           Asia     3
3            Pakistan           Asia     4
4          Bangladesh           Asia     5
..                ...            ...   ...
234           Uruguay  South America    10
235            Guyana  South America    11
236          Suriname  South America    12
237     French Guiana  South America    13
238  Falkland Islands  South America    14

[239 rows x 3 columns]

### 9.Retrieve the top 3 most populated countries in each continent.

In [63]:
pd.read_sql_query("select * from (select Name,Continent,Population,row_number() over (partition by Continent  order by Population desc) as rnk from country ) t  where rnk<=3 ",conn)

/var/folders/qm/5y4s4wyj5c9dcyd20_qy23b80000gn/T/ipykernel_3683/1953748973.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("select * from (select Name,Continent,Population,row_number() over (partition by Continent  order by Population desc) as rnk from country ) t  where rnk<=3 ",conn)

                                 Name      Continent  Population  rnk
0                               China           Asia  1277558000    1
1                               India           Asia  1013662000    2
2                           Indonesia           Asia   212107000    3
3                  Russian Federation         Europe   146934000    1
4                             Germany         Europe    82164700    2
5                      United Kingdom         Europe    59623400    3
6                       United States  North America   278357000    1
7                              Mexico  North America    98881000    2
8                              Canada  North America    31147000    3
9                             Nigeria         Africa   111506000    1
10                              Egypt         Africa    68470000    2
11                           Ethiopia         Africa    62565000    3
12                          Australia        Oceania    18886000    1
13                   Papua New Guinea        Oceania     4807000    2
14                        New Zealand        Oceania     3862000    3
15                         Antarctica     Antarctica           0    1
16  Heard Island and McDonald Islands     Antarctica           0    2
17        French Southern territories     Antarctica           0    3
18                             Brazil  South America   170115000    1
19                           Colombia  South America    42321000    2
20                          Argentina  South America    37032000    3

### 10. Find the second most populated country in each continent.

In [65]:
pd.read_sql_query("select * from (select Continent, Name, Population,row_number() over (partition by Continent order by population desc ) as rnk from country ) t where rnk=2",conn)

/var/folders/qm/5y4s4wyj5c9dcyd20_qy23b80000gn/T/ipykernel_3683/2264525223.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("select * from (select Continent, Name, Population,row_number() over (partition by Continent order by population desc ) as rnk from country ) t where rnk=2",conn)

       Continent                               Name  Population  rnk
0           Asia                              India  1013662000    2
1         Europe                            Germany    82164700    2
2  North America                             Mexico    98881000    2
3         Africa                              Egypt    68470000    2
4        Oceania                   Papua New Guinea     4807000    2
5     Antarctica  Heard Island and McDonald Islands           0    2
6  South America                           Colombia    42321000    2